### ISSUE TITLE
Please add 5 more lines to index.html

### ISSUE THREAD

**Issue by gib** [cyanharlow/purecss-francine#11]
This would bring the total lines form 1,332 up to 1337 which would add a nice Easter egg showing how 'leet this project is! Congratulations on an accomplished work of art!

**Comment by cyanharlow** [comment]
@gib  That is a goddamn brilliant idea. Done and <a href="https://github.com/cyanharlow/purecss-francine/commit/0119edec46e65871b257f04dda6c230a987c5c03">done</a>.

**Comment by gib** [comment]
Closed via https://github.com/cyanharlow/purecss-francine/commit/0119edec46e65871b257f04dda6c230a987c5c03
