### ISSUE TITLE
Tree?

### ISSUE THREAD

**Issue by captbaritone** [cyanharlow/purecss-francine#12]
I'm curious what the story is behind the tree which exists in HTML, but not in CSS. Looks like it was added in this commit: https://github.com/cyanharlow/purecss-francine/commit/cf1e17e97961620dcf53ebe87838c08ca4a35960

**Comment by cyanharlow** [comment]
@captbaritone  If this had not been shared on twitter, I would've made continuous updates on it until the day I died. I'm never fully satisfied with any art I make, and at some point I thought some background flora scenery would improve it, so I started writing some local CSS for it. Then I decided against it, then I decided to leave the elements there (sans style) in case I changed my mind again.

**Comment by captbaritone** [comment]
Awesome! So cool to hear the back story. Thanks for filling us in. You say “I _would have_ made edits until the day I died.” Does that mean the attention the project has gotten has changed your motivation to continue iterating? I can really relate to the notion of wanting to continue interating on creative projects  forever.

**Comment by cyanharlow** [comment]
It has - because now there are a bunch of screenshots saved that capture it for posterity at that one moment in time. I'm not 100% happy with it, but the general response that it's gotten lets me know that I should at least try to be content with it. Plus, I can consider it a good motivator to just make something new.

**Comment by captbaritone** [comment]
Makes sense. Thanks for taking the time to reply. Looking forward to what you start on next.
