### ISSUE TITLE
Works fine in Firefox and Safari

### ISSUE THREAD

**Issue by rbiggs** [cyanharlow/purecss-francine#14]
In your README you say it only works in Chrome. Well, it works identically in Firefox, Safari, and even MS Edge. Since you're mostly using CSS transforms, border radius and gradients, all modern browsers handle these identically. IE on the other hand is a different story. But it is a discontinued browser. Edge is evergreen like other modern browsers. Please update your README to reflex that other modern browsers can indeed render your work as expected.

**Comment by diomed** [comment]
works fine in Opera too
