### ISSUE TITLE
Graphical issues on Safari iOS 11

### ISSUE THREAD

**Issue by adoniskrasniqi** [cyanharlow/purecss-francine#8]
![ac22abb3-79a4-44b8-863f-a1274b0719cc](https://user-images.githubusercontent.com/17968705/39515697-326e4ef6-4dfb-11e8-9bf1-42cdbe9721c3.png)

**Comment by adi518** [comment]
It looks like Safari made her frown _and_ angry.

**Comment by BramVanBerkel** [comment]
I can’t open it at all on IOS Safari

**Comment by makc** [comment]
this is duplicate of #5 actually

**Comment by adoniskrasniqi** [comment]
@makc 
Different browser.

**Comment by happychameleon** [comment]
@adoniskrasniqi 
but the same web engine (because all browsers on iOS are forced to use the safari web-kit engine)

**Comment by adoniskrasniqi** [comment]
Closed because it is duplicate of #5
Thanks to @makc and @happychameleon
